name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        version: sdl2-latest
        
    - uses: actions/checkout@v3

    - name: Create build folder
      run: mkdir build

    - name: build executable
      run: make
