name: ci

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: create build dir
        run: |
          mkdir build
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev
      - name: build sed
        run: |
          make
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: create build dir
        run: |
          mkdir build
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq libsdl2-dev 
      - name: build sed
        run: |
          make
        env:
          CC: clang
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: create build dir
        run: |
          mkdir build
      - name: install dependencies
        run: brew install sdl2 pkg-config 
      - name: build sed
        run: |
          make
        env:
          CC: gcc
